### ISSUE TITLE
'ModelApiClientImpl' incorrectly implements interface 'IModelApiClient'.

### ISSUE THREAD

**Issue by stephanbruijnis** [simo101/MendixSecurityAudit#1]
Hi Simon,

I was trying to use your Mendix Security Audit but got an error on the `tsc `command it says its an incorrect implementation of the IModelApiClient. I'm running it against a Mendix 6.8.1 project.

Can you help me with this?'
With kind regards,
Stephan

```
C:\Users\Stephan\Mendix\SecurityAudit>tsc
node_modules/mendixmodelsdk/dist/sdk/internal/model-api-client.d.ts(92,22): error TS2420: Class 'ModelApiClientImpl' incorrectly implements interface 'IModelApiClient'.
  Types of property 'grantAccessByProject' are incompatible.
    Type '(projectId: string, memberOpenId: string, callback: IVoidCallback, errorCallback: IErrorCallback)...' is not assignable to type '(projectId: string, memberOpenId: string, callback: ICallback<boolean>, errorCallback: IErrorCall...'.
      Types of parameters 'callback' and 'callback' are incompatible.
```

**Comment by simo101** [comment]
Hi Stephan,

I have rewrote a lot of the functionality for this sdk script. It now supports reporting in excel for entity, microflows and pages access. It will detail every user role against module roles along with the security for the pages, entities and microflows in 3 separate excel tabs.
